name: Run Julia Simulation

on:
  push:
    branches: [ main ]

jobs:

  run:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: '1.10'

    - name: Install packages
      run: |
        julia -e 'using Pkg; Pkg.add(["Plots","FFMPEG"])'

    - name: Run simulation
      run: |
        julia wave_packet.jl